# Generated by Django 4.0.5 on 2022-06-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Movie Name')),
                ('production_year', models.PositiveIntegerField(default=1900)),
                ('director', models.CharField(choices=[('Mohamed Khan', 'Mohamed Khan'), ('Salah Abo Saif', 'Salah Abo Saif')], default='Mohamed Khan', max_length=20)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('actors', models.ManyToManyField(to='actor.actor')),
            ],
        ),
    ]
