# Generated by Django 4.0.5 on 2022-06-08 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0002_actor_birth_date'),
        ('director', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='movies', to='actor.actor'),
        ),
    ]
