# Generated by Django 4.0.5 on 2022-06-09 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default='2010-10-10', verbose_name='Date of Birth'),
        ),
    ]
